### ISSUE TITLE
Warning on Elixir v1.14

### ISSUE THREAD

**Issue by thbar** [akash-akya/unzip#11]
I'm doing a bit of preliminary testing with https://github.com/elixir-lang/elixir/releases/tag/v1.14.0-rc.1, and noticed the following warning, so I'm opening an issue to report it :

```
warning: use Bitwise is deprecated. import Bitwise instead
  lib/unzip.ex:30: Unzip
```

Happy to provide a PR if you want.

**Comment by akash-akya** [comment]
Done. Published new version as well.

Thank you for raising the issue :)

**Comment by thbar** [comment]
@akash-akya many thanks!
