### ISSUE TITLE
Feature: Support for Gzip

### ISSUE THREAD

**Issue by fireproofsocks** [akash-akya/unzip#16]
It would be nice if there were support for dealing with Gzip and Gunzip files.  Would such a feature be possible?  I'm admittedly not super familiar with the file format.

**Comment by akash-akya** [comment]
@fireproofsocks unlike zip format `.tar.gz` does not have file index similar to **central file directory**. So we can't selectively stream files like we can in zip files. To know what files that are present in the zip, we have to stream the complete file and collect files ourselves. 

We _can_ provide stream interface by streaming it twice (first to get all file names and second time to stream the specific file). But I am not sure if this mismatch makes sense from an interface perspective. Let me check this.

**Comment by akash-akya** [comment]
I will revisit this later if more users want something like this. 
For now, skipping this in favor of keeping the library simple.

Thanks!
