### ISSUE TITLE
Remove warning

### ISSUE THREAD

**Issue by sitch** [akash-akya/unzip#17]
I was attempting to use this to integrate into the bumblebee project <https://github.com/elixir-nx/bumblebee> (see PR here: <https://github.com/elixir-nx/bumblebee/pull/144>) however this library <https://github.com/akash-akya/unzip/blob/dc0bc3bc14219ddce6e5ba8f7fb3ae0d9017d7a9/lib/unzip.ex#L381> creates a bunch of unnecessary warnings on invalid datetimes

**Comment by sitch** [comment]
Could either remove the warning, make it opt-in, or set a sensible default (unix epoch)

**Comment by akash-akya** [comment]
@sitch removed the log and release new version with the change `v0.8.0`.
Can you share any sample file which was throwing this warning?

**Comment by jonatanklosko** [comment]
Hey @akash-akya! [This](https://huggingface.co/stanford-crfm/pubmedgpt/blob/main/pytorch_model.bin) is an example file, it has 10GB though. The modification date time in the file is all zeros.

**Comment by jonatanklosko** [comment]
Also, thanks for the quick fix :)
