### ISSUE TITLE
Invalid zip file, missing EOCD record but unzip -t returns okay

### ISSUE THREAD

**Issue by AntoineAugusti** [akash-akya/unzip#19]
Hello!

We're getting an error

```elixir
iex> Unzip.new(Unzip.LocalFile.open("/tmp/gtfs.zip"))
{:error, "Invalid zip file, missing EOCD record"}
```
with the following file: [gtfs.zip](https://github.com/akash-akya/unzip/files/10661553/gtfs.zip) while `unzip` seems to report that the archive is okay.

```
$ unzip -t gtfs.zip                                                                                                                                                                                     
Archive:  gtfs.zip
    testing: agency.txt               OK
    testing: calendar.txt             OK
    testing: calendar_dates.txt       OK
    testing: routes.txt               OK
    testing: shapes.txt               OK
    testing: stop_times.txt           OK
    testing: trips.txt                OK
    testing: stops.txt                OK
No errors detected in compressed data of gtfs.zip.
```

Do you know what could be wrong?

**Comment by akash-akya** [comment]
Thanks for reporting the issue and sharing a sample to test! 
I noticed that it fails to extract even with the OTP implementation `:zip.extract/1`. I'll look into this.

**Comment by akash-akya** [comment]
@AntoineAugusti, the zip file you shared does not conform to the zip spec. File has a comment at the end, but the comment length specified in the header does not match the length, making it an invalid zip file. `unzip` follow the spec more strictly compared to system tools. You can read more about this exact issue in detail here - https://github.com/thejoshwolfe/yauzl/issues/48#issuecomment-266587526. Command line is more trusting than `unzip`. You can confirm the issue by repairing the zip with `zip -FF gtfs.zip --out new.zip`. Notice that it removed this extra bytes (comment) at the end of `new.zip`.

If possible, can you share how you created this zip file (tool or library you used)?

**Comment by AntoineAugusti** [comment]
@akash-akya We didn't create this ZIP file, I'll try to get an answer!
