### ISSUE TITLE
Unzip from memory?

### ISSUE THREAD

**Issue by thbar** [akash-akya/unzip#20]
At times, I find it useful (although it won't work with huge files) to work with a binary in memory.

I wonder if it would make sense to implement a `Unzip.FileAccess` for a binary, so that things can work in RAM fully.

Unsure if this should come with the library, or just as a documentation snippet.

Maybe I'll provide an implementation if today's case I'm meeting shows up again in the future.

**Comment by akash-akya** [comment]
Hi @thbar, 
yes, that makes sense. Initially, I was mostly focused on remote files, optimizing the bandwidth usage. But this is useful too, I'll push changes soon.

**Comment by thbar** [comment]
Thank you @akash-akya!!!
