### ISSUE TITLE
CSV file chunk read with `file_stream!` |> Enum.to_list() returns deeply nested lists

### ISSUE THREAD

**Issue by christopherdbull** [akash-akya/unzip#23]
Hey, I'm seeing some weird behaviours as I use this library to parse CSV files nested inside a ZIP file.

The Zip file is handled well, the list_entries method works well. When I access one of the CSV files however, instead of being a smooth process of chunked strings, each chunk is returned as a list of lists (nested 10 deep in one case), finally with the actual string buried deeply within.

I suspect this is something to do with the Stream.transform in `unzip` but I'm not experienced enough with stream processing to figure it out - rapidly getting more experienced by the hour at this point, ha.

Happy to supply the file.

Cheers

**Comment by akash-akya** [comment]
Hey @christopherdbull 
`Zip.file_stream!/2` returns stream of [iodata](https://hexdocs.pm/elixir/1.12/IO.html#module-io-data) not binary/string. 
This is an optimization to avoid building intermediate binary if you are forwarding it to some other IO operation. Most IO operations in elixir/erlang work with iodata to take benefit of this, you can read more about it [here](https://hexdocs.pm/elixir/1.12/IO.html#module-io-data).

But if your usecase wants binary/string then you can just convert using `IO.iodata_to_binary`

```elixir
binary_stream =
  Unzip.file_stream!(zipfile, "foo.csv")
  |> Stream.map(&IO.iodata_to_binary/1)
```

**Comment by akash-akya** [comment]
I am closing this. But let me know if you still face issues.

**Comment by christopherdbull** [comment]
Thank you! Got there in the end - via a bit of a practical education on iodata and streams in elixir 😅
