### ISSUE TITLE
Error isn't given on bad zip file

### ISSUE THREAD

**Issue by cheerfulstoic** [akash-akya/unzip#25]
I've got a bad zip file where, when I try to read it off disk, `Unzip.new` returns a binary value instead of a `{:ok, _}`.  Looking at the code, I think that maybe this `with` statement is at fault:

https://github.com/akash-akya/unzip/blob/master/lib/unzip.ex#L227

If the `with` can't match that binary pattern exactly, then the non-matching binary is returned.  Maybe that `with` clause should instead call a function to parse the binary which returns `{:ok, _}` / `{:error, _}`.

I can't share the zip file, but I can say that it's a KMZ.  Also, the reason it's broken (the real problem which I'm trying to fix separately) is that I try to save the file via the code below and it ends up, for some reason, with one less byte (it goes from `52827` bytes to `52826` bytes)

```elixir
    dir = System.tmp_dir!()

    temp_path =
      "#{dir}#{Ecto.UUID.generate()}.kmz"
      |> IO.inspect(label: :temp_path)

    file_stream
    |> Enum.into(File.stream!(temp_path, []))

    {:ok, unzip} =
      Unzip.LocalFile.open(temp_path)
      |> IO.inspect(label: :a)
      |> Unzip.new()
      |> IO.inspect(label: :b)
```

**Comment by akash-akya** [comment]
Hey @cheerfulstoic, on cursory look, the issue indeed looks like as you have described. Thanks for the detailed report. 

> with one less byte (it goes from 52827 bytes to 52826 bytes)

Not sure if it helps, but for I had faced this multiple times and most of the it is to do with default option for IO being `:line`, which trims CRLF bytes. 

For `File.stream!` we have to pass bytes explicitly 
```elixir
file_stream = File.stream!("somefile", [], 2048)
```

https://hexdocs.pm/elixir/1.13/File.html#stream!/3

**Comment by cheerfulstoic** [comment]
🎉  Thanks, I tried passing in a number of bytes and it wasn't working for whatever reason.  For now I just took the `path` attribute off the file stream from the LiveView upload and that has worked well (and is less code 😉 )

And thanks for fixing this so quickly!
