### ISSUE TITLE
"Erlang error: :data_error" on an apparently valid zip file

### ISSUE THREAD

**Issue by thbar** [akash-akya/unzip#27]
Hi there!

I stumbled upon a zip file which seems (I believe) in general readable, and reported as valid by `unzip -t`, but which raises an error during parsing with `unzip`.

I am not sure yet where is the culprit (in my code, in unzip, or in the underlying Erlang libraries).

Here is a reproduction with data files.

The "bogus file" can be found at:
- https://transport-data-gouv-fr-resource-history-prod.cellar-c2.services.clever-cloud.com/40287/40287.20240401.061120.295743.zip (static content)
- https://www.data.gouv.fr/fr/datasets/r/40ee9d6c-3bb9-409e-b670-986212de63f2 (may change in the future)

```elixir
Mix.install([
  {:req, "~> 0.4.0"},
  {:unzip, "~> 0.11.0"},
  {:nimble_csv, "~> 1.2"}
])

ExUnit.start(trace: true)

defmodule Downloader do
  def local_file_name(url), do: Path.basename(url) <> ".zip"

  def cached_download!(url, local_file) do
    unless File.exists?(local_file) do
      %{status: 200} = Req.get!(url, into: File.stream!(local_file), raw: true)
    end
  end
end

defmodule UnzippingParser do
  def open_zip_file(file) do
    zip_file = Unzip.LocalFile.open(file)
    {:ok, unzip} = Unzip.new(zip_file)
    unzip
  end

  def list_entries(unzip) do
    unzip
    |> Unzip.list_entries()
  end

  def parse_and_get_headers(unzip, "stops.txt" = entry_name) do
    unzip
    |> Unzip.file_stream!(entry_name)
    |> Stream.map(&IO.iodata_to_binary/1)
    |> NimbleCSV.RFC4180.to_line_stream()
    |> NimbleCSV.RFC4180.parse_stream(skip_headers: false)
    |> Stream.take(1)
    |> Enum.at(0)
  end
end

defmodule AssertionTest do
  use ExUnit.Case

  def run_test(url) do
    local_file = Downloader.local_file_name(url)
    Downloader.cached_download!(url, local_file)

    headers = UnzippingParser.parse_and_get_headers(UnzippingParser.open_zip_file(local_file), "stops.txt")
    assert "stop_lat" in headers
  end

  test "parses first file" do
    # "GTFS" file for https://www.data.gouv.fr/en/datasets/reseau-cars-region-isere-38/
    run_test("https://www.data.gouv.fr/fr/datasets/r/40ee9d6c-3bb9-409e-b670-986212de63f2")
  end

  test "parses second file" do
    # https://www.data.gouv.fr/fr/datasets/offre-de-transport-cc-jalles-eau-bourde/
    run_test("https://www.data.gouv.fr/fr/datasets/r/6fa85772-cc88-43ae-88b9-290e2f9345ff")
  end
end
```

I will try to have a closer look at some point, but do not have the time right now, so just capturing the issue for now.

#### Checksums

```
❯ cksum *.zip
4016894865 38060335 40287.20240401.061120.295743.zip
4016894865 38060335 40ee9d6c-3bb9-409e-b670-986212de63f2.zip
22202388 136685 6fa85772-cc88-43ae-88b9-290e2f9345ff.zip
```

```
❯ unzip -t 40ee9d6c-3bb9-409e-b670-986212de63f2.zip 
Archive:  40ee9d6c-3bb9-409e-b670-986212de63f2.zip
    testing: agency.txt               OK
    testing: calendar_dates.txt       OK
    testing: feed_info.txt            OK
    testing: routes.txt               OK
    testing: shapes.txt               OK
    testing: stops.txt                OK
    testing: stop_times.txt           OK
    testing: transfers.txt            OK
    testing: trips.txt                OK
No errors detected in compressed data of 40ee9d6c-3bb9-409e-b670-986212de63f2.zip.
```

```
❯ unzip -t 6fa85772-cc88-43ae-88b9-290e2f9345ff.zip 
Archive:  6fa85772-cc88-43ae-88b9-290e2f9345ff.zip
    testing: agency.txt               OK
    testing: trips.txt                OK
    testing: stops.txt                OK
    testing: stop_times.txt           OK
    testing: shapes.txt               OK
    testing: calendar_dates.txt       OK
    testing: calendar.txt             OK
    testing: routes.txt               OK
No errors detected in compressed data of 6fa85772-cc88-43ae-88b9-290e2f9345ff.zip.
```

**Comment by thbar** [comment]
Forgot the stack trace:

```
AssertionTest [repro.exs]
  * test parses second file (13.6ms) [L#58]
  * test parses first file (5.3ms) [L#53]

  1) test parses first file (AssertionTest)
     repro.exs:53
     ** (ErlangError) Erlang error: :data_error
     code: run_test("https://www.data.gouv.fr/fr/datasets/r/40ee9d6c-3bb9-409e-b670-986212de63f2")
     stacktrace:
       :zlib.inflateEnd_nif(#Reference<0.1143709808.1199177734.32420>)
       (unzip 0.11.0) lib/unzip.ex:188: anonymous fn/1 in Unzip.decompress/2
       (elixir 1.16.2) lib/stream.ex:1039: Stream.do_transform_inner_list/7
       (elixir 1.16.2) lib/stream.ex:1038: Stream.do_transform_inner_list/7
       (elixir 1.16.2) lib/stream.ex:1828: Enumerable.Stream.do_each/4
       (elixir 1.16.2) lib/stream.ex:1038: Stream.do_transform_inner_list/7
       (elixir 1.16.2) lib/stream.ex:1828: Enumerable.Stream.do_each/4
       (elixir 1.16.2) lib/enum.ex:4506: Enum.slice_enum/5
       (elixir 1.16.2) lib/enum.ex:479: Enum.at/3
       repro.exs:49: AssertionTest.run_test/1
       repro.exs:55: (test)
```

**Comment by thbar** [comment]
Likely source:

https://github.com/akash-akya/unzip/blob/689a1ca7a134ab2aeb79c8c4f8492d61fa3e09a0/lib/unzip.ex#L188

**Comment by akash-akya** [comment]
Hey @thbar, I think the issue in this case is the file stream is not completely consumed, and the stream is getting closed early because of `Stream.take(1)`. 
The call `:zlib.inflateEnd(z)` asserts that [decompression is completed](https://www.erlang.org/doc/man/zlib#inflateEnd-1). Also, to check the CRC and ensure data integrity, we have to consume it completely.

For the sample test file, If you change it to consume completely, it does not throw error.

```diff
    |> NimbleCSV.RFC4180.parse_stream(skip_headers: false)
+   |> Enum.to_list()
    |> Stream.take(1)
```

**Comment by thbar** [comment]
Hi @akash-akya! 

Ahh I didn't think about that right away, because I'm working "en masse" with 440 zip files, and only 29 of them caused troubles with that same `Stream.take(1)` code!!!

It makes perfect sense. For now I will just "slurp" the complete files to work-around this!

Ultimately it would be a great feature addition to be able to interrupt the processing right in the middle, as it allows e.g. sampling (like `head -n10`) of zipped files. When processing large files (> 1GB) it could be really great!

But for now that will do, I will come back if the need arise (in which case I think e.g. passing a special caller flag to indicate that the stream will be interrupted, and handling the clean-up differently, could be a possibility).

Thank you very much for the timely answer!

**Comment by akash-akya** [comment]
> Ultimately it would be a great feature addition to be able to interrupt the processing right in the middle, as it allows e.g. sampling (like head -10) of zipped files. When processing large files (> 1GB) it could be really great!

Yeah, that does make sense from streaming pov. Maybe with a special flag like you mentioned. Do let me know if you have a such use case.
