### ISSUE TITLE
Suggestions of improvements for the project

### ISSUE THREAD

**Issue by thbar** [akash-akya/unzip#9]
Thanks for `unzip`, I'm happy to use your project!

I wonder if you would accept PR for the 2 following changes:

1. Setting up a CI with GitHub actions (CI is important to help maintenance!)
2. Removing some warnings due to recent changes in the project (see below)

Let me know what you think, happy to help at some point.

### Warnings

I got the following warnings with Elixir 1.13.4:

```
warning: use Mix.Config is deprecated. Use the Config module instead
  config/config.exs:1

Compiling 5 files (.ex)
warning: "else" shouldn't be used as the only clause in "defp", use "case" instead
  lib/unzip.ex:173
```

**Comment by akash-akya** [comment]
Hi @thbar, thanks for the raising the issue!

I'm open to suggestions and PR. But since the above suggestions were simple, I went ahead and fixed.

**Comment by thbar** [comment]
Hi @akash-akya! Thank you very much :smile:
